# Generated by Django 5.0.6 on 2024-05-15 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='is_decimal_measurable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='produced_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
