# Generated by Django 5.0.6 on 2024-05-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='symbol',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
